name: Trigger auto deployment for codex-calculator

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/codex-calculator-AutoDeployTrigger-d9b82c68-f35d-4ce8-b4fc-d3b37b83d31e.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.CODEXCALCULATOR_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: ca624031e1beacr.azurecr.io
          registryUsername: ${{ secrets.CODEXCALCULATOR_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CODEXCALCULATOR_REGISTRY_PASSWORD }}
          containerAppName: codex-calculator
          resourceGroup: codex-demo-rg
          imageToBuild: ca624031e1beacr.azurecr.io/codex-calculator:${{ github.sha }}
          
            

     

